name: new_workflow_job

on:
  push:
    branches:
      - 'feature/*'
  workflow_dispatch:
    inputs:
      target_env:
        required: true
        description: this is to input
        default: "test"
        type: choice
        options:
          - test
          - prod
jobs:
  message_job:
    name: greeting job
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "hi this is sudhkar"
      - name: checkout code
        uses: actions/checkout@v4
      - name: list_files
        run: |
          ls
        